---
title: "19º Congresso Nacional de Meio Ambiente de Poços de Caldas - References"
output: html_document
---
<style>
body {
  color: black;
  font-family: Times;
  font-size: 20px;
}
pre {
  background-color: lightgreen;
}
#TOC {
  color: darkblue;
  font-family: Times;
  font-size: 14px;
  border-color: black;
}
#header {
  color: gold;
  align: center;
}
</style>

<br>
<br>

* ALYOUSIFI, Y. et al. Trend analysis and change point detection of air pollution index in
Malaysia. **International Journal Of Environmental Science And Technology**, [S.L.], v. 19, n.
8, p. 7679-7700, 21 nov. 2021. Springer Science and Business Media LLC.
http://dx.doi.org/10.1007/s13762-021-03672-w.

* ANDREÃO, Willian Lemker; ALBUQUERQUE, Taciana Toledo de Almeida. Avoidable
mortality by implementing more restrictive fine particles standards in Brazil: an estimation using
satellite surface data. **Environmental Research**, [S.L.], v. 192, n. 110288, p. 1-11, jan. 2021.
Elsevier BV. http://dx.doi.org/10.1016/j.envres.2020.110288.
* CARSLAW, D. C.; ROPKINS, K. openair - an r package for air quality data analysis.
**Environmental Modelling & Software**, v. 27-28, n. 0, p. 52-61, 2012. ISSN 1364-8152.

* COEN, M. C.; BIGI, A. **MannKendallTrends**: MannKendall trends for geophysical time
series. [S.l.], 2021. R package version 1.1.0. Disponível em: <https://mannkendall.github.io/R/>.

* Conselho Nacional do Meio Ambiente (CONAMA). Resolução nº 491, de 19 de novembro de 2018. **Dispõe sobre padrões de qualidade do ar. Diário Oficial [da] República Federativa do Brasil** - 1, Brasília, DF, 2018. ISSN 1677-7042. Disponível em:
<https://www.in.gov.br/materia/-/asset_publisher/Kujrw0TZC2Mb/content/id/51058895>. Acesso
em: 02 mar. 2022.

* Companhia Ambiental do Estado de São Paulo (CETESB). **QUALAR**: Sistema de informações
da qualidade do ar. 2022. Disponível em: <https://qualar.cetesb.sp.gov.br/qualar/home.do>.
Acesso em: 01 mar. 2022

* Fundação Estadual do Meio Ambiente (FEAM). **Informações Complementares das Estações**. 2020. Disponível em:
<http://www.feam.br/images/stories/2020/QUALIDADE_DO_AR/Tabela_Inform%C3%A7%C3%B5es_Complementares_das_Esta%C3%A7%C3%B5es.xlsx>. Acesso em: 01 mar. 2022.